In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Sun Mar  9 21:07:01 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
from psutil import virtual_memory
ram_gb = virtual_memory().total / 1e9
print('Your runtime has {:.1f} gigabytes of available RAM\n'.format(ram_gb))

if ram_gb < 20:
  print('Not using a high-RAM runtime')
else:
  print('You are using a high-RAM runtime!')

Your runtime has 54.8 gigabytes of available RAM

You are using a high-RAM runtime!


In [ ]:

!pip -qqq install pydub
!pip -qqq install tensorboard
!pip -qqq install visualkeras
!pip -qqq install --upgrade keras
!pip -qqq install --upgrade keras tensorflow


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 997.4/997.4 kB 25.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 34.1 MB/s eta 0:00:00


In [ ]:
import os
import math
import numpy as np
import librosa
import json
import pandas as pd
from termcolor import colored
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf
import visualkeras
from keras.utils import plot_model
from datetime import datetime
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn import svm
from sklearn.svm import SVC
import pickle
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from IPython.display import Audio
from scipy.io import wavfile
import scipy
import soundfile as sf
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report
from pydub import AudioSegment
import random

import os
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from sklearn.metrics import classification_report, confusion_matrix
from pydub import AudioSegment
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [ ]:
base_dir = '/content/drive/MyDrive/ASE_Dataset_Folder'
#sound_dir = os.path.join(base_dir, 'Sound_1_Sec_5_Files')

image_dir = os.path.join(base_dir,  'Mel_Images_1_Sec')
train_dir = os.path.join(image_dir, 'Train/Sounds')
test_dir = os.path.join(image_dir, 'Test/Sounds')

# Check if the train_dir exists
if os.path.exists(image_dir):
  if os.path.exists(train_dir):
    if os.path.exists(test_dir):
      print(f"train_dir exists: {image_dir}")
  else:
    print(f"train_dir does not exist: {train_dir}")

#train_dir = r"/content/drive/MyDrive/ASE_Dataset_Folder/Images_1_Sec/Train"
#test_dir = r"/content/drive/MyDrive/ASE_Dataset_Folder/Images_1_Sec/Test"



# List files in the train directory
train_files = os.listdir(train_dir)
print(f"Files in train directory: {train_files[:10]}")  # Print first 10 files

# List files in the test directory
test_files = os.listdir(test_dir)
print(f"Files in test directory: {test_files[:10]}")  # Print first 10 files


train_dir exists: /content/drive/MyDrive/ASE_Dataset_Folder/Images_1_Sec
Files in train directory: ['Explosion', 'Emergency_alarm', 'Gun_Shots', 'glass_breaking', 'thunderstorm', 'dog', 'wind']
Files in test directory: ['Gun_Shots', 'Emergency_alarm', 'Explosion', 'dog', 'glass_breaking', 'thunderstorm', 'wind']


In [ ]:

from tensorflow.keras.preprocessing.image import ImageDataGenerator

num_classes = 7
height = 128
n_fft = 2048
hop_length = 256
sr = 22050
T = 1

hop_size_sec = hop_length / sr
audio_length_samples = T * sr

width = 1 + int((audio_length_samples - n_fft) / hop_length)

channels = 3


train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)


train_datagen = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

test_datagen = ImageDataGenerator()

batch_size = 32

train_generator = train_datagen.flow_from_directory(
        train_dir,
        target_size=(height, width),
        batch_size=batch_size,
        class_mode='categorical')

test_generator = test_datagen.flow_from_directory(
        test_dir,
        target_size=(height, width),
        batch_size=batch_size,
        class_mode='categorical',
        shuffle=False)

# Output the results
print(f"Found {train_generator.samples} images for training.")
print(f"Found {test_generator.samples} images for testing.")

# Check if generators are yielding data
if len(train_generator) == 0:
    raise ValueError(f"Train generator is empty. Check the directory: {train_dir}")
if len(test_generator) == 0:
    raise ValueError(f"Test generator is empty. Check the directory: {test_dir}")


cnn_model = tf.keras.Sequential()
cnn_model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(height, width, channels)))
cnn_model.add(tf.keras.layers.MaxPooling2D((2, 2)))
cnn_model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))
cnn_model.add(tf.keras.layers.MaxPooling2D((2, 2)))
cnn_model.add(tf.keras.layers.Conv2D(128, (3, 3), activation='relu'))
cnn_model.add(tf.keras.layers.MaxPooling2D((2, 2)))
cnn_model.add(tf.keras.layers.Flatten())

# RNN model
rnn_model = tf.keras.Sequential([
    tf.keras.layers.Reshape((width, height * channels), input_shape=(height, width, channels)),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32, activation='relu', return_sequences=True)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32, activation='relu', return_sequences=True)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32, activation='relu')),
    tf.keras.layers.BatchNormalization()
])

# Combine CNN and RNN models
model = tf.keras.Sequential([
    tf.keras.layers.Reshape((1, height, width, channels), input_shape=(height, width, channels)),
    tf.keras.layers.TimeDistributed(cnn_model),  # TimeDistributed applies the CNN model to each time step
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32, activation='relu')),  # RNN on top of CNN features
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy', 'precision', 'recall', 'f1_score'])

epochs = 200
metrics_data = []

for epoch in range(epochs):
    print(f"Epoch {epoch + 1}/{epochs}")

    train_generator.reset()

    history = model.fit(
        train_generator,
        steps_per_epoch=len(train_generator),
        epochs=1,
        verbose=1,
        validation_data=test_generator,
        validation_steps=len(test_generator))

    # Get metrics from history
    accuracy = history.history['accuracy'][0]
    precision = history.history['precision'][0]
    recall = history.history['recall'][0]

    f1_score_tensor = history.history['f1_score'][0]
    f1_score_value = np.mean(f1_score_tensor)

    # Store metrics in a list
    metrics_data.append([accuracy, precision, recall, f1_score_value])

model.save('/content/drive/MyDrive/CRNN/Third_test/al-emadi_crnn_standardized_unknown_3_test.keras')




Found 1111 images belonging to 7 classes.
Found 477 images belonging to 7 classes.
Found 1111 images for training.
Found 477 images for testing.


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/200


/usr/local/lib/python3.11/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


35/35 ━━━━━━━━━━━━━━━━━━━━ 687s 20s/step - accuracy: 0.2045 - f1_score: 0.1844 - loss: 1.9710 - precision: 0.4745 - recall: 0.0124 - val_accuracy: 0.3019 - val_f1_score: 0.1313 - val_loss: 2.7752 - val_precision: 0.3857 - val_recall: 0.2830
Epoch 2/200
35/35 ━━━━━━━━━━━━━━━━━━━━ 20s 586ms/step - accuracy: 0.4145 - f1_score: 0.3242 - loss: 1.6027 - precision: 0.8469 - recall: 0.0929 - val_accuracy: 0.4361 - val_f1_score: 0.3537 - val_loss: 1.5341 - val_precision: 0.6875 - val_recall: 0.2075
Epoch 3/200
35/35 ━━━━━━━━━━━━━━━━━━━━ 20s 576ms/step - accuracy: 0.4777 - f1_score: 0.4187 - loss: 1.4126 - precision: 0.8546 - recall: 0.1678 - val_accuracy: 0.4906 - val_f1_score: 0.3808 - val_loss: 1.2925 - val_precision: 0.6192 - val_recall: 0.3103
Epoch 4/200
35/35 ━━━━━━━━━━━━━━━━━━━━ 20s 569ms/step - accuracy: 0.5563 - f1_score: 0.5067 - loss: 1.2300 - precision: 0.7837 - recall: 0.2535 - val_accuracy: 0.4780 - val_f1_score: 0.3974 - val_loss: 1.2017 - val_precision: 0.6680 - val_recall: 0.34

In [ ]:
import csv

# Save metrics to a CSV file
csv_filename = '/content/drive/MyDrive/CRNN/Third_test/training_metrics_2_test.csv'

with open(csv_filename, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Accuracy', 'Precision', 'Recall', 'F1 Score'])
    writer.writerows(metrics_data)

print(f"Training metrics saved to {csv_filename}")

loss, accuracy, precision, recall, f1_score = model.evaluate(test_generator)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)
print("Test Precision:", precision)
print("Test Recall:", recall)
print("Test F1 Score:", f1_score)

Training metrics saved to /content/drive/MyDrive/CRNN/Third_test/training_metrics_2_test.csv
15/15 ━━━━━━━━━━━━━━━━━━━━ 5s 339ms/step - accuracy: 0.8353 - f1_score: 0.4657 - loss: 0.7285 - precision: 0.8447 - recall: 0.8328
Test Loss: 0.8948010206222534
Test Accuracy: 0.8218029141426086
Test Precision: 0.8319149017333984
Test Recall: 0.8197064995765686
Test F1 Score: tf.Tensor(
[0.91999996 0.6709677  0.86842096 0.8190475  0.8372092  0.69999987
 0.8633093 ], shape=(7,), dtype=float32)


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# Model and directories configuration
num_classes = 7
height = 128
n_fft = 2048
hop_length = 256
sr = 22050
T = 1

hop_size_sec = hop_length / sr
audio_length_samples = T * sr
width = 1 + int((audio_length_samples - n_fft) / hop_length)
channels = 3
batch_size = 32

# Load the pre-trained model
model_path = '/content/drive/MyDrive/CRNN/Third_test/al-emadi_crnn_standardized_unknown_3_test.keras'
model = tf.keras.models.load_model(model_path)

# Test Data Generator
test_datagen = ImageDataGenerator()
test_dir = '/content/drive/MyDrive/ASE_Dataset_Folder/Images_1_Sec/Test/Sounds'  # Ensure this path is correct
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(height, width),
    batch_size=batch_size,
    class_mode='categorical',
    shuffle=False)

# Evaluate the model
results = model.evaluate(test_generator)
print(f"Test Loss: {results[0]}")
print(f"Test Accuracy: {results[1]}")
if len(results) > 2:
    print(f"Additional Metrics:")
    for metric, value in zip(model.metrics_names[2:], results[2:]):
        print(f"{metric.capitalize()}: {value}")

# Predicting classes
predictions = model.predict(test_generator)
predicted_classes = np.argmax(predictions, axis=1)

# True class indices
true_classes = test_generator.classes

# Compute confusion matrix
conf_matrix = confusion_matrix(true_classes, predicted_classes)
print("\nConfusion Matrix:")
print(conf_matrix)

# Get class labels
class_labels = list(test_generator.class_indices.keys())

# Classification Report
print("\nClassification Report:")
print(classification_report(true_classes, predicted_classes, target_names=class_labels))

# Calculate accuracy for each class
class_accuracy = {}
for i, class_label in enumerate(class_labels):
    correct_indices = np.where(true_classes == i)[0]
    correct_predictions = np.sum(predicted_classes[correct_indices] == i)
    total_samples = len(correct_indices)
    class_accuracy[class_label] = correct_predictions / total_samples if total_samples > 0 else 0.0

# Print accuracy for each class
print("\nAccuracy for each class:")
for class_label in class_labels:
    print(f"{class_label}: {class_accuracy[class_label]:.4f}")


Found 477 images belonging to 7 classes.
15/15 ━━━━━━━━━━━━━━━━━━━━ 8s 384ms/step - accuracy: 0.8353 - f1_score: 0.4657 - loss: 0.7285 - precision: 0.8447 - recall: 0.8328
Test Loss: 0.8948010206222534
Test Accuracy: 0.8218029141426086
Additional Metrics:
15/15 ━━━━━━━━━━━━━━━━━━━━ 6s 370ms/step

Confusion Matrix:
[[115   6   0   0   2   1   0]
 [  4  52   1   4   8   4   5]
 [  0   1  33   0   0   0   1]
 [  5   3   0  43   5   0   0]
 [  1   2   2   1  54   0   0]
 [  0  11   4   1   0  35   7]
 [  1   2   1   0   0   2  60]]

Classification Report:
                 precision    recall  f1-score   support

Emergency_alarm       0.91      0.93      0.92       124
      Explosion       0.68      0.67      0.67        78
      Gun_Shots       0.80      0.94      0.87        35
            dog       0.88      0.77      0.82        56
 glass_breaking       0.78      0.90      0.84        60
   thunderstorm       0.83      0.60      0.70        58
           wind       0.82      0.91      